FROM centos:7

ENV NODEJS_VERSION=10

EXPOSE 3000

WORKDIR /usr/src/app

COPY package.json package-lock.json* ./

RUN yum install -y http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum install -y npm

RUN npm install && npm cache clean --force

RUN yum update

RUN yum install curl

COPY . .

CMD [ "node", "./bin/www" ]
